### ISSUE TITLE
Extension simply not working

### ISSUE THREAD

**Issue by Raigiku** [tomoki1207/vscode-pdfviewer#31] opened 2018-11-10 23:29 UTC
The extension simply doesn't work
VSCode version: 1.28.2
OS: Windows 10 64-bits
![2018-11-10_18-24-29](https://user-images.githubusercontent.com/31873735/48307214-1938e380-e516-11e8-85b6-7679afac1f4e.gif)

**Comment by weixu000** [comment] 2018-11-11 05:12
I have the same problem. Is there any help?
Thanks.

**Comment by jypjypjypjyp** [comment] 2018-11-12 08:19
I use win10 18277, and my Edge pdf viewer is broken too. I think the problem is caused by Edge.

**Comment by mac40** [comment] 2018-11-12 08:53
> I use win10 18277, and my Edge pdf viewer is broken too. I think the problem is caused by Edge.

I am experiencing the same issue but my Edge pdf viewer works fine so i think it is too early to say whether the two are correlated or not

**Comment by tomoki1207** [comment] 2018-11-13 02:05
Sorry guys, we had a bug about local resource path for windows.
The plugin was updated to 0.4.1, could you try it again?

**Comment by mac40** [comment] 2018-11-13 16:35
now it stop at this step
![screenshot_2](https://user-images.githubusercontent.com/15819726/48428036-6f05c980-e76a-11e8-9d59-20509e5845f2.png)

**Comment by rodmoncada** [comment] 2018-11-13 18:52
This bug is also affecting Linux :(

**Comment by Axinex** [comment] 2018-11-14 22:57
Using vsCode v. 1.29.0 now results in any PDFs opening to a black screen.
![2018-11-14_15-55-21](https://user-images.githubusercontent.com/42529760/48518157-ea788100-e825-11e8-8271-4c480aeb1338.gif)

**Comment by tomoki1207** [comment] 2018-11-15 07:30
@rodmoncada Please create new issue with your environment. (OS, VSCode version, Plugin version and so on...)

**Comment by Raigiku** [comment] 2018-11-15 18:40
@tomoki1207 I reinstalled and this is what shows up
![image](https://user-images.githubusercontent.com/31873735/48573976-f0309e00-e8db-11e8-8ae4-f9a38b7712ee.png)
Then when I alt-tabbed back to chrome to upload that image and came back to VSCode, the previous text changed to this:
![image](https://user-images.githubusercontent.com/31873735/48573981-f58de880-e8db-11e8-961c-0db4ae58f560.png)

**Comment by tomoki1207** [comment] 2018-11-16 02:57
@rodmoncada @Axinex 
This behavior (the blank page is shown after PDF viewer was shown in a moment) might be caused by the size of pdf file is too large.
Could you try it with lighter one?(like https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)

I think these files were opened well until update, the new VSCode api seems to has implicit size limit.
I'll continue investigation to avoid it.

**Comment by Axinex** [comment] 2018-11-16 03:21
> 
> 
> @rodmoncada @Axinex
> This behavior (the blank page is shown after PDF viewer was shown in a moment) might be caused by the size of pdf file is too large.
> Could you try it with lighter one?(like https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)
> 
> I think these files were opened well until update, the new VSCode api seems to has implicit size limit.
> I'll continue investigation to avoid it.

The file you linked does appear to open correctly, but I am concerned that should the file size limit be the root cause, then this file size limit is very low, as the file I am able to replicate my issue with is only 51KB in size. I have linked the problematic file below.
[palette.pdf](https://github.com/tomoki1207/vscode-pdfviewer/files/2587819/palette.pdf)

**Comment by tomoki1207** [comment] 2018-11-16 03:39
@Axinex 
Thank you reporting.
As you said, palette.pdf is broken in my mac too. And the pdf file that is shown well is larger than it.
It seems that problem not caused by size but caused by pdf format or else. 🤔

**Comment by johnking** [comment] 2018-12-17 20:04
I could not open any *.pdf file after installing this extension, I am using Mac-pro

vs-code version is shown inside the screen-shot as well.

[
![screen shot 2018-12-17 at 15 02 15](https://user-images.githubusercontent.com/1787137/50112256-ca652480-020c-11e9-9163-ec8b3425d9b3.png)
](url)

**Comment by tomoki1207** [comment] 2018-12-18 05:32
@johnking Did you mean "after updating this extension"?
We had a bug in open pdf, so fixed it and extension is updated just now.
Please try re-open a pdf file. If "Do you want to open it anyway?" shown like your screenshot, click this link.

**Comment by johnking** [comment] 2018-12-18 13:03
It works! thanks so much @tomoki1207

**Comment by MayrJo** [comment] 2019-01-04 09:41
Just right-click on the files tab in the corner and click "View PDF".

**Comment by forivall** [comment] 2019-01-14 22:31
I just barely installed the extension and I get the same problem as reported by @Raigiku in https://github.com/tomoki1207/vscode-pdfviewer/issues/31#issuecomment-439146307

Name: vscode-pdf
Id: tomoki1207.pdf
Description: Display pdf file in VSCode.
Version: 0.4.3
Publisher: tomoki1207
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf

Platform: OSX

![screen shot 2019-01-14 at 2 29 49 pm](https://user-images.githubusercontent.com/760204/51145550-0211bd00-1809-11e9-9888-8f838824c9ec.png)

![screen shot 2019-01-14 at 2 31 26 pm](https://user-images.githubusercontent.com/760204/51145575-1655ba00-1809-11e9-912a-bbd5750cc65a.png)

**Comment by D1ceWard** [comment] 2019-02-19 16:30
Same behavior, black screen (persit even after uninstall/reinstall)
![screenshot from 2019-02-19 17-26-08](https://user-images.githubusercontent.com/8332823/53030663-8f30dd00-346b-11e9-835f-ef44d4427692.png)
vscode ver: 1.31.1
vscode-pdf ver: 0.4.3
os: Arch Linux

**Comment by PharaohJoe** [comment] 2019-02-20 02:16
Also getting a black screen. I reverted to version 0.4.0 and it works. Seems that any version past 0.4.0 doesn't work

**Comment by Skeiceee** [comment] 2019-02-20 13:14
> Also getting a black screen. I reverted to version 0.3.0 and it works. Seems that any version past 0.3.0 doesn't work

0.3.0 Working,  Only working 0.3.0

**Comment by tomoki1207** [comment] 2019-02-25 04:20
@all Sorry a lot to keep you waiting.
It was updating for recovery to work just now. Please try it.
We'll continue to welcome to your report.
Thank you.

**Comment by Skeiceee** [comment] 2019-02-26 01:21
> @ALL Sorry a lot to keep you waiting.
> It was updating for recovery to work just now. Please try it.
> We'll continue to welcome to your report.
> Thank you.

Work, nice.

**Comment by tomoki1207** [comment] 2019-02-26 05:29
Closing as fixed it.
If you still have problems, please create another issue.

**Closed by tomoki1207** 2019-02-26 05:29 UTC
