### ISSUE TITLE
Strange behavior on Linux

### ISSUE THREAD

**Issue by serl** [tomoki1207/vscode-pdfviewer#5] opened 2017-01-05 13:47 UTC
I have the latest version of VS Code, on Ubuntu 16.04:

    Version 1.8.1
    Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
    Date 2016-12-19T14:41:20.664Z
    Shell 1.4.6
    Renderer 53.0.2785.143
    Node 6.5.0

 The extension version is 0.1.0.

The behavior is quite strange: when I click on a PDF file, the Vivaldi browser is launched... and it's not even my default browser..!
Additionally, it looks like every time the PDF tab on VSCode gets the focus, a new browser window is launched (always on the start page), while the PDF tab itself remains black.
(I checked on Help>Developer tools, there are no errors in console)

Feel free to ask for more info

**Comment by tomoki1207** [comment] 2017-01-06 00:17
@serl Thank you for report.
Is that behavior even occurred when disable this extension? Also, has that encountered in other situations and/or operations (ex. on markdown preview)?

**Comment by serl** [comment] 2017-01-06 09:29
Never saw it before.
Markdown works just fine, and for PDFs I see gibberish without the extension.

**Comment by serl** [comment] 2017-01-09 10:21
I've an extra hint!
It looks like the default application opening `.js` files is... Vivaldi.

**Comment by tomoki1207** [comment] 2017-01-10 04:50
Thank you a lot for investigating.
I'll investigate after setting up Ubuntu in the virtual environment.
Please tell me, if you find other hints.

**Comment by tomoki1207** [comment] 2017-01-10 04:51
mistaked 💦

**Comment by serl** [comment] 2017-01-10 10:14
Ok, so first, I have to confess that I'm not using plain Ubuntu, but I substituted the graphical environment with I3wm. I have no idea if the bug appears also in the vanilla Ubuntu.

Anyway, I used the power of F5 to track down the bug a little bit. In particular, I tried to comment out the iframe line in `src/pdfProvider.ts` and put a static text instead, it works as expected, meaning: I see the text where it is supposed to be (in VS Code).
The, I tried to put back the iframe, but with an empty html file instead of the pdf viewer; the bug appears.

So: the iframe is the culprit (or VS Code itself...)

**Comment by tomoki1207** [comment] 2017-01-11 01:54
Now, this extension looks not work fine on my plain Ubuntu on virtualbox.
On this environment, any browser doesn't launched, but PDF tab is blank in VSCode.

This bug seems caused by iframe's src path and it'll fixed by changing [this line](https://github.com/tomoki1207/vscode-pdfviewer/blob/master/src/pdfProvider.ts#L27) to `src="file://${this.getPath...`.
(Maybe that path is misunderstood as site root relative path.)
Additional, this change not affect to Windows environment.

@serl 
If you have a source code, could you change it like to above?
It is lucky if this behavior will fixed simultaneously. And I'll include this fix next release.

**Comment by serl** [comment] 2017-01-11 09:55
I confirm, it fixes the problem! :)

Thanks a lot

**Closed** 2017-01-11 10:28 UTC
Labels: bug
