### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by shunmian** [tomoki1207/vscode-pdfviewer#38] opened 2019-01-30 08:12 UTC
It will be great if this extension supports dark mode.

**Comment by frankspanks** [comment] 2019-02-22 11:26
I have the same problem too.. going to try find a way to fix it!

**Comment by pdtran3k6** [comment] 2019-02-23 14:04
@shunmian like inverted pdf pages (white text, black background)?

**Comment by shunmian** [comment] 2019-02-24 12:05
@pdtran3k6 Yes, exactly, which is more friendly for long time reading.

**Comment by tomoki1207** [comment] 2019-02-25 04:37
duplicate of #22.

**Closed by tomoki1207** 2019-02-25 04:37 UTC
