### ISSUE TITLE
PDF is no longer displayed

### ISSUE THREAD

**Issue by hsk** [tomoki1207/vscode-pdfviewer#39] opened 2019-02-08 01:50 UTC
PDF is no longer displayed when I version up VS Code today.

**Comment by janosh** [comment] 2019-02-08 17:21
Same problem.

**Comment by Supportic** [comment] 2019-02-09 10:20
I see the raw PDF string for a moment and then it turns into a blank black page. (newest vscode version)

**Comment by DiegoSalazar** [comment] 2019-02-09 17:43
I just installed this extension and it does not display PDFs, I just get a blank page and an error "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding."

**Comment by jmcd73** [comment] 2019-02-09 22:16
> I see the raw PDF string for a moment and then it turns into a blank black page. (newest vscode version)

Downgrading to 0.4.2 doesn't fix the issue. I am on MacOS 10.14.3 (Mojave)

**Comment by phenomax** [comment] 2019-02-10 12:22
+1 here on High Sierra.

**Comment by jtkiley** [comment] 2019-02-10 15:16
Same here.

macos 10.14.3 
vscode 1.31.0

Newest versions of these extensions:

```
$ code --list-extensions
ban.spellright
eamodio.gitlens
James-Yu.latex-workshop
kirozen.wordcounter
kylebarron.stata-enhanced
ms-python.anaconda-extension-pack
ms-python.python
notZaki.pandocciter
redhat.vscode-yaml
rust-lang.rust
tomoki1207.pdf
zeithaste.cursorCharCode
```

**Comment by aflofo** [comment] 2019-02-11 17:39
Not a solution but I use this extension religiously for homework so I just downgraded vscode to the November release until the issue is resolved
https://code.visualstudio.com/updates/v1_30

**Comment by tomoki1207** [comment] 2019-02-15 04:05
It seems related to #31.
Until this time some specific files could not be opened, all files can't be opened now.
I close this issue because duplicate. I'll investigate for this problem.
Thanks for support.

**Closed by tomoki1207** 2019-02-15 04:05 UTC
